const API=window.SPC_API;const WA=window.SPC_WHATSAPP;const EMAIL=window.SPC_EMAIL;
const $=(s)=>document.querySelector(s);
async function loadNews(){try{const r=await fetch(API+'/api/public/news');const{items}=await r.json();const el=$('#news');if(!items?.length){el.innerHTML='<p class="muted">Sem notícias.</p>';return}
el.innerHTML=items.map(n=>`<div class="card"><span class="badge">${n.categoria||'geral'}</span><h3>${esc(n.titulo)}</h3>${n.resumo?`<p class="muted">${esc(n.resumo)}</p>`:''}<p style="margin-top:10px">${esc(n.conteudo)}</p><p class="muted" style="margin-top:8px">${new Date(n.created_at).toLocaleDateString('pt-BR')}</p></div>`).join('')}catch(e){$('#news').innerHTML='<p class="muted">Erro ao carregar.</p>'}}
async function loadNotices(){try{const r=await fetch(API+'/api/public/notices');const{items}=await r.json();$('#notices').innerHTML=items.length?items.map(n=>`<div class="card"><span class="badge ${n.prioridade}">${n.prioridade}</span><h3>${esc(n.titulo)}</h3><p>${esc(n.mensagem)}</p></div>`).join(''):'<p class="muted">Sem avisos.</p>'}catch(e){}}
async function loadFaq(q=''){try{const r=await fetch(API+'/api/public/faq'+(q?'?q='+encodeURIComponent(q):''));const{items}=await r.json();$('#faq-list').innerHTML=items.length?items.map(f=>`<details class="faq-item"><summary>[${esc(f.categoria)}] ${esc(f.pergunta)}</summary><p style="margin-top:8px">${esc(f.resposta)}</p></details>`).join(''):'<p class="muted">Nenhum resultado.</p>'}catch(e){}}
async function loadQuestions(){try{const r=await fetch(API+'/api/public/questions');const{items}=await r.json();$('#duvidas').innerHTML=items.length?items.map(q=>`<div class="card"><h3>${esc(q.pergunta)}</h3>${q.resposta?`<p style="margin-top:8px">${esc(q.resposta)}</p>`:'<p class="muted">Aguardando resposta...</p>'}<p class="muted" style="margin-top:8px">${q.autor||'Anônimo'} · ${esc(q.categoria||'')}</p></div>`).join(''):'<p class="muted">Mural vazio.</p>'}catch(e){}}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
async function sendMessage(e){e.preventDefault();const f=e.target;const fd=new FormData(f);const out=$('#msg-out');out.textContent='Enviando...';out.className='msg';try{const r=await fetch(API+'/api/public/messages',{method:'POST',body:fd});const j=await r.json();if(j.ok){out.textContent=j.message;out.className='msg ok';f.reset()}else{out.textContent=j.error||'Erro';out.className='msg err'}}catch(err){out.textContent='Erro de conexão';out.className='msg err'}}
async function sendQuestion(e){e.preventDefault();const f=e.target;const fd=new FormData(f);const out=$('#duv-out');out.textContent='Enviando...';try{const r=await fetch(API+'/api/public/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});const j=await r.json();if(j.ok){out.textContent=j.message;out.className='msg ok';f.reset();loadQuestions()}else{out.textContent=j.error||'Erro';out.className='msg err'}}catch(err){out.textContent='Erro de conexão';out.className='msg err'}}
function quickWA(tipo){const msgs={ferias:'Olá SPC, gostaria de informações sobre minhas férias.',licenca:'Olá SPC, preciso de orientação sobre licença.',lts:'Olá SPC, preciso encaminhar atestado/LTS.',frequencia:'Olá SPC, preciso justificar/regularizar frequência.',outro:'Olá SPC, preciso de atendimento.'};window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msgs[tipo]||msgs.outro)}`,'_blank')}
function quickMail(tipo){const subj={ferias:'[Férias] Solicitação',licenca:'[Licença] Solicitação',lts:'[LTS] Atestado',frequencia:'[Frequência] Regularização',outro:'Atendimento SPC'};window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subj[tipo]||subj.outro)}`}
document.addEventListener('DOMContentLoaded',()=>{loadNews();loadNotices();loadFaq();loadQuestions();
$('#form-msg')?.addEventListener('submit',sendMessage);$('#form-duv')?.addEventListener('submit',sendQuestion);
$('#faq-search')?.addEventListener('input',(e)=>loadFaq(e.target.value));});
window.quickWA=quickWA;window.quickMail=quickMail;
